favicon: favicon/favicon.ico

# Size: 100x100
avatar: imgs/avatar.jpg

# Icon use fontawesome class
menu:
  Home:
    path: /
    icon: home
  Archives:
    path: /archives
    icon: archive
  Tags:
    path: /tags
    icon: tag

# Icon use fontawesome class
links:
  Github:
    link: https://github.com/cwxyz007
    icon: github
  Email:
    link: mailto:fantasy.cwxyz@gmail.com
    icon: envelope

# Google analytics
ga:
  active: true
  id: 'UA-101492756-1'

# Creative commons license
cclicense:
  text: 版权声明：本文使用 @license 协议
  # All in lower case
  cc by-nc: https://creativecommons.org/licenses/by-nc/2.0/deed.zh
