favicon: favicon/favicon.ico

footer: |
  <p> Powered by
    <a class="footer-link" href="https://github.com/cwxyz007/hexo-simple-template" target="_blank" rel="noopener">Simple</a>
    and
    <a class="footer-link" href="https://hexo.io" target="_blank" rel="noopener">Hexo</a>
    , Made By
    <a class="footer-link" href="https://github.com/cwxyz007" target="_blank" rel="noopener">@Fantasy</a>
  </p>

# Size: 100x100
avatar: imgs/avatar.jpg

# Icon use fontawesome class
menu:
  Home:
    path: /
    icon: home
  Archives:
    path: /archives
    icon: archive
  Tags:
    path: /tags
    icon: tag

# Icon use fontawesome class
links:
  Github:
    link: https://github.com/cwxyz007
    icon: github
  Email:
    link: mailto:x.li.gem@gmail.com
    icon: envelope

# Google analytics
ga:
  active: true
  id: 'UA-101492756-1'

# Creative commons license
cclicense:
  text: 版权声明：本文使用 @license 协议
  # All in lower case
  cc by-nc 4.0: https://creativecommons.org/licenses/by-nc/4.0/deed.zh
