favicon: favicon/favicon.ico

# 100x100
avatar: imgs/avatar.jpg

# menu
# icon use fontawesome class
menu:
  Home:
    path: /
    icon: home
  Archives:
    path: /archives
    icon: archive
  Tags:
    path: /tags
    icon: tag

# links
# icon use fontawesome class
links:
  Github:
    link: https://github.com/cwxyz007
    icon: github
  Email:
    link: mailto:844067636@qq.com
    icon: envelope

# google analytics
ga:
  active: true
  id: 'UA-101492756-1'
